### ISSUE TITLE
some tiny questions about funcPrivateCompareMPC() and debugPC()

### ISSUE THREAD

**Issue by zzz130981** [snwagh/securenn-public#10]
Hello, I have used debugPC() and I get:
![2020-02-15 22-09-37 的屏幕截图](https://user-images.githubusercontent.com/30946222/74589384-e1391e00-503f-11ea-8e59-efcc563a7340.png)
I have serval tiny questions, hoping for your respond:
1.Is my terminal's output right?

2.What values are stored in the vector [share_m](https://github.com/snwagh/securenn-public/blob/51c4d3378ed2aa6ab53d3c0a8344704698743481/src/Functionalities.cpp#L1685)? I know that each 64 bit of it represents a number, so in my opinion, the values of it is:
1 2 4 8 16 32 64 128 256 512

3. What is the meaning of "1"？Does it mean that the ith number of  share_m <= r？If so, I should understand my terminal's output one by one as follow:
1:1 <= 5
0: 2 > 6
1: 4 <= 7
1: 8 <= 8
1: 16 <= 9
0: 32 > 10
1: 64 <= 11
0: 128 > 12
0: 256 > 13
1: 512 <= 14
This is obviously wrong. Could you tell where I am wrong, thank you!

**Comment by snwagh** [comment]
PC functionality has a blinding factor betaPrime. The actual comparison answer should be faithful to beta XOR betaPrime.

**Comment by zzz130981** [comment]
It seems useless.
I have make beta XOR betaPrime , namely changed this line(https://github.com/snwagh/securenn-public/blob/51c4d3378ed2aa6ab53d3c0a8344704698743481/src/Functionalities.cpp#L1701) to be:
```c++
cout << (int) (beta[i]^betaPrime[i]) << endl; 
```
After the invocation of debugPC(), the terminal still outputs:
![2020-02-18 12-23-47 的屏幕截图](https://user-images.githubusercontent.com/30946222/74703849-8a9f3000-5249-11ea-9fd0-2eb878c6f1f1.png)

**Comment by snwagh** [comment]
Please print all the values and see if the debugging leads you anywhere. Be careful in every step. Note that these are shares (you can't just print them, you've to reconstruct them).
