### ISSUE TITLE
bug of debugMax() or funcMaxMPC()

### ISSUE THREAD

**Issue by zzz130981** [snwagh/securenn-public#11]
Just like I did in #7 , I invoked debugMax() in the main function. 
As you know, what it does is to find the value and index of the MAX in an array a({0,1,0,4,5,3,10,6,41,9}), the expect result is "max:41 maxIndex:4".
However, I only got:
![2020-02-18 19-52-55 的屏幕截图](https://user-images.githubusercontent.com/30946222/74736425-a88e8400-528d-11ea-8646-efa2e696df02.png)

**Comment by 0xlimE** [comment]
My project partner and I figured out that you can make this give the right result if you call debugComputeMSB(); before

**Comment by zzz130981** [comment]
Yes, you're right!
So will it works if you run debugMSB() or funcComputeMSB3PC() before funcMaxMPC() is invokeed?

**Comment by zzz130981** [comment]
> My project partner and I figured out that you can make this give the right result if you call debugComputeMSB(); before

Yes, you're right!
So will it works if you run debugMSB() or funcComputeMSB3PC() before funcMaxMPC() is invokeed?

**Comment by 0xlimE** [comment]
I have no idea how any of this ends up working together so I cant help you.

**Comment by zzz130981** [comment]
> I have no idea how any of this ends up working together so I cant help you.

I have tried invoke debugMSB() or funcComputeMSB3PC() before funcMaxMPC(), however, it does not work.

Have you try debugPC()？I think it does not work, either.
