### ISSUE TITLE
About error Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by WeiViming** [snwagh/securenn-public#15]
Hello, @snwagh . When I run `make`, it goes well. But I am confused when I try to run `make standalone`, it gives me the fellow message. The other two commands also give me the same error. What's wrong with it? Thank you!
```bash
❯ make standalone
./BMRPassive.out STANDALONE 4 files/parties_localhost files/keyA files/keyAB files/data/mnist_data_8_samples files/data/mnist_labels_8_samples files/data/mnist_data_8_samples files/data/mnist_labels_8_samples
make: *** [makefile:36: standalone] Segmentation fault (core dumped)
```

**Comment by snwagh** [comment]
The standalone code (as well as the 4PC) is more legacy. 

Seg fault usually indicated some illegal memory access (accessing an array beyond it's size etc.). You will have to trace the function call and tell me which line it occurred and I can point you the possible reason but just from this, it is virtually impossible to tell the source of the seg fault.

**Comment by WeiViming** [comment]
I am amazed that after I modify the makefile and change "-O3" to "-O0", rebuild the project, it works well!!  Thank you for your help! :)
