### ISSUE TITLE
About secret sharing

### ISSUE THREAD

**Issue by mialuyao** [snwagh/securenn-public#17]
I couldn't find any information about secret sharing, which has been stated in the paper.
Could you please point me in the direction of any relevant documentation?

**Comment by joyoFeng** [comment]
@mialuyao the origin paper: https://eprint.iacr.org/2018/442.pdf, and for Honest-Majority Maliciously version refer to : https://arxiv.org/abs/2004.02229, which adopts `msb`  optimization. 
The author recommend this reps: https://github.com/snwagh/falcon-public ~

**Comment by mialuyao** [comment]
Thank you. 
I get it.
