### ISSUE TITLE
[BUG]: Question on the Share Convert protocol when input is -1?

### ISSUE THREAD

**Issue by llCurious** [snwagh/securenn-public#18]
hi, @snwagh . I recently read the paper SecureNN and have a question on the proposed ReLU protocol.

In short, ReLU depends on the share convert protocol, which converts the share from Z_L to Z_{L-1}. What if the input is -1, which is encoded as L-1 over Z_L. It seems  that -1 will be converted to 0 over Z_{L-1}? Consequently, the MSB(-1) = MSB(0) =0, which is wrong.

**Comment by snwagh** [comment]
@llCurious I think there is some technicality there. In SecureNN itself, that edge case is handled as follows (referencing this [PDF](https://eprint.iacr.org/2018/442.pdf)): 

- Algorithm 4 explicitly assumes value $\neq -1$
- Algorithm 6, Step 1 ensures that the above condition is true when applying $\Pi_{\mathsf{SC}}$

It would be good to trace the flow when input is -1, thus $c$ in algorithm 6 is -2 and see how the math works out.

**Comment by llCurious** [comment]
Thx to you quick reply. I do miss the Step 1 in Algo-6 which multiplies all the input by 2 to avoid the occurrence of -1.
