### ISSUE TITLE
Question about the processor being used by the code

### ISSUE THREAD

**Issue by ppourali** [snwagh/securenn-public#2]
Hello,
 
Nice work! I just have a question about the performance. If I run your code on a machine with a GPU device, will the code utilize GPU for the computations (especially the linear computations) or it is not designed to consider GPU (i.e., tensorflow vs. tensorflow-gpu)? I'm asking because the performance will be affected taking into account the device that is running the layers.

I assume the machine you ran in your paper (Amazon EC2) did not have GPU devices, right?

Thanks,
Parsa

**Comment by snwagh** [comment]
In its current form, it does not benefit from GPUs. The performance will indeed be different with and without the support. The Amazon EC2 numbers quoted in the paper do not use GPU devices. 

It would be useful to add this feature. A simple addition won't be too hard given that there exist standard GPU libraries out there and that is all that the MPC would require (at least for linear operations)
