### ISSUE TITLE
question about "the appropriate command"

### ISSUE THREAD

**Issue by zzz130981** [snwagh/securenn-public#3]
Hello, your work is excellent! 
However, I am a beginner in c++. So I have some tiny and simple questions.(maybe stupid)
1. I wonder if I want to do this machine learning work  in a local network , what's "the appropriate command"?
2. If I have some similar questions such as 1.  how can I get "the appropriate command"？Might you offer a more detailed use manual?
3. I only have a PC, how can I build a local network? I plan to use VMware Workstation, build two or three virtual machines, set Network Connection to be "NAT" and modify files/parties_LAN. Is there a better solution？

**Comment by snwagh** [comment]
Thanks zzz130981! 

Why don't you start a new issue for each of your questions and I can respond to them individually? And don't worry, there are no stupid questions, your questions will help the broader community in using this codebase. For starters, I've added quick responses below: 

1.  You can just run `make abcTerminal` from the command line and that will run all 3 parties locally on the same machine and print the output of Party 0 to the terminal. You can view it [here](https://github.com/snwagh/securenn-public/blob/master/makefile#L86). I remember re-writing the makefile and can aim to update it with the improved script that allows for seamless localhost, LAN and WAN experiments. 
2. Please add it as a new github issue with what you would like and I/others can try to add it in.
3. The easiest would be to run 3 terminal instances on localhost which is what the above response to point 1 would do.
