### ISSUE TITLE
How to do floating-point and negative number arithmetic？

### ISSUE THREAD

**Issue by zzz130981** [snwagh/securenn-public#4]
Hello!
If I want to calculate a polynomial such as: 0.9258x^2-0.4642x+0.686, x ∈ [-2.0, 2.0], how to do it？

It seems that there is reaveal() in your system, but I cannot find it now. Does it exist? I know the principle behind  this kind of function: Firstly, there is a number called  precision such as 8192 etc. Then the floating-point is magnified by 8192 times and then rounded. Lastly, it is divided by 8192. So do I need to implement it by myself?

However, as for  negative number, I have no idea.

**Comment by snwagh** [comment]
The basic datatype is uint64_t and so the negative numbers are the ``large'' numbers. In other words, if your precision is 13 bits (corresponding to 8192), then 1 is the real number 2^-13 and -1, which when typecast to myType will be 2^64 - 1 (c++ will consider these two numbers the same) which correspond to the real number -2^-13
