### ISSUE TITLE
question about usage of negative numbers

### ISSUE THREAD

**Issue by zzz130981** [snwagh/securenn-public#9]
Hi, I'm having trouble using this system to manipulate negative numbers. The scenario is that I want to recover a shared negative number , but only get 0 instead of correct ans(-1,-3) 

My code is as follow：

```c++
int main(int argc, char** argv)
{
	 parseInputs(argc, argv);
/****************************** AES SETUP and SYNC ******************************/ 
	aes_indep = new AESObject(argv[4]);
	aes_common = new AESObject(argv[5]);
	aes_a_1 = new AESObject("files/keyD");
	aes_a_2 = new AESObject("files/keyD");
	aes_b_1 = new AESObject("files/keyD");
	aes_b_2 = new AESObject("files/keyD");
	aes_c_1 = new AESObject("files/keyD");
	aes_parallel = new ParallelAESObject(argv[5]);

	if (!STANDALONE)
	{
		initializeCommunication(argv[3], partyNum);
		synchronize(2000000);	
	}

	if (PARALLEL)
		aes_parallel->precompute();
/****************************** myWork*****************************/ 
	size_t size = 2;
	vector<myType> data(size);

	if(partyNum == PARTY_A) {
		data[0] =  floatToMyType(-0.5);
		data[1] =  floatToMyType(-1.5);
	} 	

	if(partyNum == PARTY_B) {
		data[0] =  floatToMyType(-0.5);
		data[1] =  floatToMyType(-1.5);
	} 	


	if(PRIMARY) {
		funcTruncate2PC(data, FLOAT_PRECISION, size, PARTY_A, PARTY_B);
		funcReconstruct2PC(data, data.size(), "data is");
	}
	
/****************************** CLEAN-UP ******************************/ 
	delete aes_common;
	delete aes_indep;
	delete aes_a_1;
	delete aes_a_2;
	delete aes_b_1;
	delete aes_b_2;
	delete aes_c_1;
	delete aes_parallel;
	if (partyNum != PARTY_S)
		deleteObjects();

	return 0;
}
```

I only got：

![2020-02-15 20-35-41 的屏幕截图](https://user-images.githubusercontent.com/30946222/74587896-0f643100-5033-11ea-8693-831ba963c902.png)

I have tried what you said in #4(-1=2^64-1), I assign 2^64-0.5 and 2^64-1.0 to p0 and p1 instead of -0.5 and -1.0, and the "myWork" section of modified main() function is as follow:

```c++
	size_t size = 2;
	vector<myType> data(size);
	float a = (1<<64)-0.5;
	float b = (1<<64)-1.0;
	if(partyNum == PARTY_A) {
		data[0] =  floatToMyType(a);
		data[1] =  floatToMyType(b);
	} 	
	if(partyNum == PARTY_B) {
		data[0] =  floatToMyType(a);
		data[1] =  floatToMyType(b);
	} 	
	if(PRIMARY) {
		funcTruncate2PC(data, FLOAT_PRECISION, size, PARTY_A, PARTY_B);
		funcReconstruct2PC(data, data.size(), "data is");
	}
```
The result has no change:
![2020-02-15 21-47-17 的屏幕截图](https://user-images.githubusercontent.com/30946222/74589041-d204a100-503c-11ea-8d17-3834916a7214.png)

In order to figure this out, I studied the numbers at the bit level and wanted to find what happen in shifting a number **FLOAT_PRECISION** bits to the left and forcing it to **myType**, here is my code:

```c++
	float a = 13;
	printf("a=%f\n", a);
	bitset<BIT_SIZE>  aBits = bitset<BIT_SIZE> (a);
	for(int i = 63; i >= 0; i--) cout << aBits[i];
	cout << endl;

	//#define floatToMyType(a) ((myType)(a * (1 << FLOAT_PRECISION)))
	a = a * (1 << FLOAT_PRECISION);
	aBits = bitset<BIT_SIZE> (a);
	for(int i = 63; i >= 0; i--) cout << aBits[i];
	cout << endl;

	a = (myType)a;
	aBits = bitset<BIT_SIZE> (a);
	for(int i = 63; i >= 0; i--) cout << aBits[i];
	cout << endl;
```

When a is positive, everything works:

![2020-02-15 21-24-29 的屏幕截图](https://user-images.githubusercontent.com/30946222/74588684-92888580-5039-11ea-85a6-f9d8540b6431.png)

However, when a is negative, all bits are zero?!
![2020-02-15 21-46-15 的屏幕截图](https://user-images.githubusercontent.com/30946222/74589027-abdf0100-503c-11ea-87ed-b3dc8b376b24.png)
So I am completely confused, I wonder how you operate negative numbers and how can I operate negative numbers to achieve my goal——to recover the shared negative numbers.

**Comment by snwagh** [comment]
Change the following `a = (myType)a;` into `myType b = (myType)a;` 
and then the following line into `aBits = bitset<BIT_SIZE> (b);` 

`a` is defined for the entire execution of the code to be a `float`
